spring:
  application:
    name: stream-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: playground
  security:
    user:
      name: scott
      password: 12345
server:
  port: 8088